# Gets all Composers
GET http://localhost:5000/api/composers
###
# Create another Composer
POST http://localhost:5000/api/composers
Content-Type: application/json

{
  "firstName": "Daniel",
  "lastName": "Jameson",
  "country": "IRELAND",
  "genre": "CLASSICAL",
  "gender": "MALE",
  "dateOfBirth": "1993-07-01",
  "dateOfDeath": "2024-01-01"
}
###
# Update a Composer
PUT http://localhost:5000/api/composers/1
Content-Type: application/json

{
  "firstName":"Jeff",
  "lastName":"Goldblum",
  "country":"AUSTRALIA",
  "genre": "JAZZ",
  "gender":"MALE",
  "dateOfBirth":"1862-08-01",
  "dateOfDeath":"1918-03-01"
}
###
# Search for Composer 1
GET http://localhost:5000/api/composers/1
###
# No ID corresponding to 69420, Does Not Work, Isn't supposed to.
GET https://localhost:5000/api/composers/69420
###
# Delete a Composer - Works.
DELETE http://localhost:5000/api/composers/7
###